### ISSUE TITLE
CMIP6 easterlies

### ISSUE THREAD

**Issue by julia-neme** [adele157/easterlies-collaborative-project#12]
**Comparison against JRA55 for the historical period (1958 - 2015):**

Done:

- Zonal and meridional winds (fields and zonal average)
- Along-slope wind (along the 1000m isobath)
- Seasonal cycle in different regions
- Time series of annual averages in different regions

To do:

- Select models by skill
- Trends

**Comment by julia-neme** [comment]
Before going into looking at what the easterlies look in different SSP's, I started looking at how different CMIP6 models compare to JRA55 for the historical period (1958 - 2015). Over the continent seems to be where the models have low performance in both, zonal and meridional componentes. Zonal averages however may be a bit deceitful for our purposes (on shelf processes) because the coastline is not zonal.

![historical-wind-mean](https://user-images.githubusercontent.com/51519847/125027658-efbb2600-e0c9-11eb-9dff-2aecc7b9ab77.png)
![historical-zonal-avg](https://user-images.githubusercontent.com/51519847/125027678-f6e23400-e0c9-11eb-9785-74db8953787a.png)

So an alternative to working in _lat lon_ space (i.e. zonal and meridional winds) is to project the winds in the orientation of the continental shelf and work with those. I could project them fairly easy onto the 1000m isobath (consistent with Hazel and Stewart 2019)

![u_long_1000](https://user-images.githubusercontent.com/51519847/125027891-6821e700-e0ca-11eb-9fef-5adcf0c5292d.png)

**But I'm not sure how to do the equivalent for the entire continental shelf**. I can't use the topography because its too noisy on  the shelf.... any ideas would be very welcome!

**Comment by julia-neme** [comment]
Here's a mask of the continental shelf: 

![Screenshot_20210709_145211](https://user-images.githubusercontent.com/51519847/125028179-eaaaa680-e0ca-11eb-807d-5df19c7a180d.png)

**Ideally I would like at every gridpoint, the mean orientation of the shelf in that region...**

**Comment by adele157** [comment]
I think this has been mentioned before, but just putting it down here for completeness, and possibly this might help to answer [Paul's question of whether the perturbation doing what we want](https://github.com/adele157/easterlies-collaborative-project/issues/20#issuecomment-880361224). 

Are there any CMIP (or possibly AMIP even?) models that have a high resolution atmosphere? As a first check, how does the spatial pattern of winds in those higher resolution models compare with JRA? Do they capture the small scale features along the coastline that are related to the katabatics? 

Then as a second step, if the high-res models do capture the spatial structure of the winds well, how do the winds in those models change in the future? Do they simulate the same, nearly zonally uniform, southward shift of the westerlies that the CMIP6 multi-model does? Or is there more spatial structure in the wind change in those models?

**Comment by julia-neme** [comment]
The highest resolution the CMIP6 model's have is 100km, which I am guessing its not enough?

**1. Spatial pattern**

As you can see in the figures below, the spatial pattern of zonal winds are OK in CMIP when compared to JRA, the differences are in magnitude rather than pattern. Meridional winds are not that good, particularly in the Amundsen-Bellinghausen and Ross Seas. 

![uas_mean_cmip6highres-jra55-abs](https://user-images.githubusercontent.com/51519847/127287952-b34475f4-4ba2-4c07-9401-efd320c6e0d5.png)

![vas_mean_cmip6highres-jra55-abs](https://user-images.githubusercontent.com/51519847/127288648-1c78d9b5-89a6-4cf0-9491-c79d90747e4a.png)

**2. Small scale**

The figures above are a bit hard to interpret, so I've zoomed in the regions of #16 . Colors are wind speed for JRA, and wind speed *anomalies* for CMIP6. Therefore, a red (blue) anomaly is a stronger (weaker) wind. The vectors show the direction of the wind, but their size is normalized to make the plot less messy.

*Amundsen-Bellinghausen*

The predominant wind in this region is in the off-shelf direction. Disregarding wind speed, some of these models capture direction accurately (I'd say INM-CM5-0, FGOALS-f3-L, EC-Earth3-CC, EC-Earth3-Veg, EC-Earth3, MPI-ESM1-2-HR and BCC-CSM2-MR). Others have a portion of the shelf, between 100W-80W where the wind is predominantly zonal instead of the meridional direction you can see in JRA. 

![wind-amundsen_cmip6highres-jra55](https://user-images.githubusercontent.com/51519847/127289418-1820d893-9876-4ae0-8b6d-ec8e9346033b.png)

*Adelie land*

In this region there are much bigger differences in wind speed than in the Amundsen. And I can see variation in wind direction as well, but I'm not sure how "significant" these are. 

![wind-adelie_cmip6highres-jra55 (1)](https://user-images.githubusercontent.com/51519847/127291504-3d15308b-b360-43bd-b44d-86f20abc354e.png)

*Prydz*

Again, quite big differences in wind magnitude, and I'd say the direction seems ok.. (note I am describing what I see on the shelf only)

![wind-prydz_cmip6highres-jra55](https://user-images.githubusercontent.com/51519847/127292557-fa36894e-ffe4-41f7-bb30-ac5f01ad0d08.png)

I am not sure if this approach is the best way of assessing whether or not the perturbation is doing what we want, any suggestions of better plots is super welcome.

**Comment by julia-neme** [comment]
**Historical period trends**

![uas-jra_cmip6mmm-historical-trends](https://user-images.githubusercontent.com/51519847/129113914-283859ac-5bd5-4341-a0fe-dcb52af11a3a.png)
![vas-jra_cmip6mmm-historical-trends](https://user-images.githubusercontent.com/51519847/129113924-5fbedac2-bb1c-4704-92b0-dfea9224d7ee.png)

**SSP2-4.5 and SSP5-8.5 minus historical**
![uas-cmip6-ssps_historical](https://user-images.githubusercontent.com/51519847/129113938-0ff9e57a-244a-4201-b3e2-ab44859196f0.png)
![vas-cmip6-ssps_historical](https://user-images.githubusercontent.com/51519847/129113944-7fd7d6e5-4cad-4d0f-a0c9-be42471d7953.png)

**Comment by julia-neme** [comment]
### Projections (SSP2-4.5 and SSP5-8.5)

Differences with historical period show:
 - Southward shift of the westerlies (red colors in zonal plot)
 - Decrease of the off-shore winds in western Ross Sea, eastern Antarctic Peninsula, Amundsen Bellinghausen Seas.
 - Increase of the off-shore winds in the eastern Ross Sea, a portion of the Weddell, and Prydz Bay
 - There seems to be an alternating pattern in 90E-180E that I don't quite understand.

![uas-cmip6-ssps_historical (1)](https://user-images.githubusercontent.com/51519847/129125357-5e88b09a-76e7-4bca-9f1f-fd224b590dd8.png)
![vas-cmip6-ssps_historical (1)](https://user-images.githubusercontent.com/51519847/129125359-5d9138aa-51eb-45b3-a47f-02852aeab247.png)

**Comment by StephenGriffies** [comment]
Amazing figures @julia-neme . 

Please remind me: does ERA show patterns similar to JRA55-do?  I believe you checked already but with to be sure.

**Comment by julia-neme** [comment]
Hi @StephenGriffies, yes [mean patterns](https://github.com/adele157/easterlies-collaborative-project/issues/29#issuecomment-890837646) of ERA5 and JRA55-do are similar! JRA55-do has larger wind speeds in general than ERA5. And there are also some differences in [trends](https://github.com/adele157/easterlies-collaborative-project/issues/29#issuecomment-890839819) in a couple of regions.
