### ISSUE TITLE
MLD change

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#14]
Create maps of mixed layer depth change around Antarctica.

**Comment by julia-neme** [comment]
![mld-mean](https://user-images.githubusercontent.com/51519847/125232008-1c1bb000-e31f-11eb-8c0d-540058241047.png)

**Comment by adele157** [comment]
Nice, can you do one zoomed in on the shelf too (maybe masked north of the 1000m isobath), so we can see the change in the shelf DSW formation mixed layers? Also, for the shelf, might be interesting to see summer (just pick a single month e.g. Feb) and winter change separately also.

**Comment by julia-neme** [comment]
![image1067](https://user-images.githubusercontent.com/51519847/125234495-360bc180-e324-11eb-9404-fbf812a60d2a.png)
