### ISSUE TITLE
Wind stress change

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#15]
Plot maps and zonal averages of the tau_x and tau_y stress on the ocean.

**Comment by julia-neme** [comment]
Mean for the 15 year period:

![tau_xy-ryf-mean](https://user-images.githubusercontent.com/51519847/125035416-2185ba00-e0d5-11eb-8151-9b3a51dc770a.png)

Easterlies UP minus RYF for the 15 years:

![tau_xy-easup-mean](https://user-images.githubusercontent.com/51519847/125035439-29455e80-e0d5-11eb-99a9-8c8ba8da1460.png)

Easterlies DOWN minus RYF for the 15 years:

![tau_xy-easdown-mean](https://user-images.githubusercontent.com/51519847/125035425-25194100-e0d5-11eb-9a53-6171a014cc8d.png)

Zonal averages:

![image843](https://user-images.githubusercontent.com/51519847/125035631-66a9ec00-e0d5-11eb-827f-41f450c35bc7.png)

**Comment by adele157** [comment]
Nice! Yes, I think it would be nice to do these for the JRA forcing files also ([there's another issue for that here where Matt suggested vector plots actually](https://github.com/adele157/easterlies-collaborative-project/issues/3)). That way we have some idea of the expected impact of the winds on sea ice also.

**Comment by StephenGriffies** [comment]
Very nice images.  

It would indeed be nice to see what is pure wind stress and what is under-ice stresses.  Perhaps one only needs to apply an ice mask.  

Also, small comment: it would be useful to colour the land light gray to help distinguish land from ocean.  As there is white currently in the ocean colormap, it can be tough in some places to know what is land and what is ocean.

**Comment by julia-neme** [comment]
I think that the model calculates **relative** stresses, weighted by sea ice concentration. So, tau is:

$\tau = \alpha \tau_{ice\ocean} + (1-\alpha) \tau_{air/ocean}$ 

The figures below are purely wind stress (calculated from the forcing files), but unlike tau_x and tau_y this is **total** stress. I think that in spite of this, in the zonal averages you can see how sea ice dampens the stress (wind + ice < wind). Spatial patterns seem very much alike..

![tau_xy_wind-ryf-mean](https://user-images.githubusercontent.com/51519847/125218700-d2bf6680-e306-11eb-967f-59707bdf3adf.png)
![tau_xy_wind-easup-mean](https://user-images.githubusercontent.com/51519847/125218704-d5ba5700-e306-11eb-86c9-2653da9870f4.png)
![tau_xy_wind-easdown-mean](https://user-images.githubusercontent.com/51519847/125218708-d7841a80-e306-11eb-8ed9-d4b9912c0923.png)
![image871](https://user-images.githubusercontent.com/51519847/125218767-eb2f8100-e306-11eb-9006-cbb9721abf55.png)
