### ISSUE TITLE
Cross-slope density (etc) transects

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#16]
Plot cross-slope transects (latitude-depth plots) of e.g. velocities / isopycnals / temp / salt for some select locations around Antarctica.

**Comment by adele157** [comment]
Here's an overview map of the transects below. I've colour-coded the transects by the sign of the bottom temperature change in the UP experiment. Magenta transects warm at the bottom, orange transects cool at the bottom. 

![map_bottom_temp_with_transect_locations](https://user-images.githubusercontent.com/8506963/126576720-b2eaf0bf-1841-480f-93fe-cb5f681c9874.jpg)

The bottom warming regions (circled in red) are all located downstream of DSW formation locations, and I think the warming here can be simply explained as a result of the change in vertical heat flux as the lower overturning cell increases in the UP simulation (i.e. more cold/fresh waters exported to depth results in warmer/saltier surface waters and cooler/fresher abyssal waters). This is what the magenta transects show. The surface (actually this extends down to 1000m or so downstream) warming signal can propagate a fair way downstream along the shelf/upper slope. This is the same mechanism I have been looking at in detail on the West Antarctic Peninsula downstream of the Weddell DSW formation. Here we are seeing the same response with a smaller magnitude at all the DSW sites. The Ross Sea warming doesn't propagate very far along the shelf (i.e. it doesn't reach East Antarctica at all). I suspect this is because the shelf at Cape Adare is very narrow and there isn't much connectivity along the shelf there (this is what Hannah has been finding with her particles).

The bottom cooling regions in the UP simulation I don't have a good explanation for yet. The cooling seems strongest in regions that have warm intrusions in the control simulation (i.e. Amundsen / Totten / Vincennes). The temperature and salinity changes in these regions seem to be a result of isopycnal heaving. Below about 200m depth (this depth varies for different regions), the isopycnals are pushed down against the coast (i.e. what might be expected for increasing easterlies), driving cooling and freshening below ~200m on the shelf. However, above ~200m in these regions, the isopycnals move upwards, which I don't really understand. Perhaps these regions have less warm CDW intrusions in the UP simulation, because the ASC has strengthened?

One good thing is that there seems to be consistency among each of the two types of transect (orange and magenta in above figure), so perhaps there's just 2 main dynamical responses going on here.

However, there are also a lot of sign changes in the bottom temperature in East Antarctica (i.e. more warm regions not linked to DSW formation sites). I haven't looked into these.

**Comment by adele157** [comment]
Transects for regions with bottom warming in the UP simulation that are downstream of DSW formation sites:

Mertz:
![Mertz](https://user-images.githubusercontent.com/8506963/126577515-d7effdd7-f187-4497-894f-10745583538a.png)

PrydzE:
![PrydzE](https://user-images.githubusercontent.com/8506963/126577527-18f5c3d1-0ece-4919-bb1c-f84279ce5971.png)

PrydzW:
![PrydzW](https://user-images.githubusercontent.com/8506963/126577531-eead9fc8-c4f1-4cf4-99c9-cc2baf7680dd.png)

**Comment by adele157** [comment]
Transects for regions with bottom cooling in the UP simulation:

AmundsenE:
![AmundsenE](https://user-images.githubusercontent.com/8506963/126577588-1098a68e-ea13-400f-9114-cf5caa0c1409.png)

AmundsenW:
![AmundsenW](https://user-images.githubusercontent.com/8506963/126577593-08694848-5a05-40b6-a1fc-b77371ca149b.png)

Totten:
![Totten](https://user-images.githubusercontent.com/8506963/126577599-6f29794f-820c-4f65-af02-808603ad2cf2.png)

Vincennes Bay:
![Vincennes](https://user-images.githubusercontent.com/8506963/126577603-60198cbf-a13d-4ea0-ab82-5ceab30a96ff.png)

**Comment by StephenGriffies** [comment]
These are very thorough and I like your idea for the warming.  

One thing that might give more hints for the cooling, and could further support the warming, is to produce animations.  Perhaps you have done that already.  

Does the anomaly appear "out of nowhere", which is what I recall thinking when Paul showed me his wind experiments from the 2014 paper, then we realized it was changes to Ekman and that was why everything seemed to appear so fast around the continent.  

Perhaps here the spatial variations in Ekman changes might be part of the story.  The wind changes are more nuanced than those from Paul's experiments, so there might be more Ekman upwelling in some regions and more downwelling elsewhere.  I know that Paul mapped Ekman for these expts and there was a lot of noise.  Perhaps some smoothing could offer more hints.

**Comment by adele157** [comment]
Good suggestions Steve. Let's put animations and Ekman pumping smoothing on the list for next week's hackathon.
