### ISSUE TITLE
JRA55-do vs ERA Interim

### ISSUE THREAD

**Issue by julia-neme** [adele157/easterlies-collaborative-project#26]
**Mean fields**

The coincident period of these two products is 1979 - 2015. The spatial pattern of the mean zonal and meridional winds are very similar, differing mostly in magnitude. The exception being the regions I highlighted on the figures below:
1. A quite large (in my opinion) difference in the zonal winds in the Ross Sea + a small scale recirculation (?) that doesn't appear clearly in ERA.
![uas-mean](https://user-images.githubusercontent.com/51519847/127583486-2e6f6ed0-746f-41c6-9e50-65c5e14b1f09.png)

2. A slightly different pattern in the Bellinghausen at around 140W in the meridional winds + larger differences in magnitude in other regions
![vas-mean](https://user-images.githubusercontent.com/51519847/127583708-17e73d99-7033-4ade-8ba0-5591fd44d0a5.png)

**Climatology**

Next thing is looking at the seasonal anomalies.
1. Seasonal fields of zonal winds have a similar pattern overall, except in the regions I highlighted where the anomalies are of opposite sign in both reanalysis, again in the Amundsen-Bellinghausen and Ross. Other differences I can see are mostly in magnitude, i.e. amplitude of the seasonal cycle. For example, East Antarctica until around 150E displays a more pronounced seasonal cycle in JRA than ERA. 
![uas-clim](https://user-images.githubusercontent.com/51519847/127584027-6edafda6-b2e6-4133-972a-a3d7f063de2a.png)

2. Meridional wind climatology seems to differ mostly, again, in the Ross Sea during winter. I guess that makes sense due to the lack of obs? Its interesting to see how the katabatics in East Ant. are stronger during MAM and weaker during DJF.
![vas-clim](https://user-images.githubusercontent.com/51519847/127584138-0c3dce1f-5c5a-4a05-a5dd-79976d502b7c.png)

**Comment by julia-neme** [comment]
**Trends**

*Note: JRA trends are different from what I showed in the meeting because these are for 1979 - 2015 and the meeting ones where 1958 - 2019.*

Zonal wind trends are very different between products, specially over the continent. However, since we are interested in the shelf part, I'd highlight that JRA shows much stronger trends than ERA in the Ross Sea (weakening) and the Amundsen-Bellinghausen (strengthening). Also on the eastern side of the Peninsula.
![uas-jra55_vs_erai-historical-trend](https://user-images.githubusercontent.com/51519847/127467580-d7ba920a-645a-4bc5-ae16-78c57caa5495.png)

Meridional wind trends are **very** different between products. Conflicting regions are again, oh surprise, the Ross and the Amundsen-Bellinghausen, but also the shelf at around 100E. In the Ross, JRA shows a very strong intensification of the northward winds coastally, and a band of weakening a bit more offshore, and ERA is showing the opposite. In the Am-Bel, JRA shows intensification of off-shore winds, ERA nothing. At around 100E JRA shows a weakening of the off-shore winds, ERA nothing.
![vas-jra55_vs_erai-historical-trend](https://user-images.githubusercontent.com/51519847/127468616-6bbc50ab-1985-4945-8d99-60d5e73562d4.png)

**Comment by julia-neme** [comment]
The trends can be divided into seasons, like Hazel et al. The largest differences are in those same regions, particularly for MAM and JJA. I'd also say that the differences are largest for the meridional wind than the zonal:

![uas-jra55_vs_erai-historical-trends-seasonal](https://user-images.githubusercontent.com/51519847/127469334-15808083-d6f5-400c-a621-eca6ad4b078f.png)
![vas-jra55_vs_erai-historical-trends-seasonal](https://user-images.githubusercontent.com/51519847/127469464-942ab17a-5e66-4b66-ba9a-72bae1331532.png)

**Comment by julia-neme** [comment]
Perhaps a better way to visualize this making focus on the continental shelf is divide the shelf in regions and averaging to get a time series for each of them. These are the regions I chose, defined by Hannah for her particles:

![basins-reference (1)](https://user-images.githubusercontent.com/51519847/127471173-6668a35f-76ec-4b76-a826-7ffacd0608d3.png)

And if we look at the time series of yearly averages for zonal wind we can see opposite trends in the Ross Sea, in the Amundsen and to a lesser extent East Antarctica 03.

![uas_onshelf-regions-yearly](https://user-images.githubusercontent.com/51519847/127471441-2f63e749-6cbf-47b1-b3ee-521fdf998f6c.png)

Looking at the meridional winds, you can see much larger differences in magnitude than for the zonal winds, and the different trends as well. Again, opposite in the Amundsen.

![vas_onshelf-regions-yearly](https://user-images.githubusercontent.com/51519847/127471765-ef2a6223-76f8-469b-997d-fbeb0fd40a97.png)

**Comment by adele157** [comment]
Wow, very comprehensive Julia, nice one! Given the meridional winds are so much larger in JRA, I expect we may simulate a lot less DSW formation in the proposed ERA-forced simulation. Now I wonder which product is more accurate?

A small note, is there 50deg of longitude in East Antarctica missing from your maps?

**Comment by matthew-england-unsw** [comment]
Wonderful analyses thanks Julia!   The CMIP6 projections will be great to check as well, to help motivate (or refine) our experimental design.  Something like 2081-2100 minus some baseline period before ozone depletion effects kicked in (at the meeting yesterday I suggested minus 1981-2000, but that's already once ozone depletion has shifted the westerlies).   So maybe 2081-2100 minus 1951-1970.

**Comment by julia-neme** [comment]
> Wow, very comprehensive Julia, nice one! Given the meridional winds are so much larger in JRA (also the zonal winds in the DSW forming regions), I expect we may simulate a lot less DSW formation in the proposed ERA-forced simulation. Now I wonder which product is more accurate?
> 
> A small note, is there 50deg of longitude in East Antarctica missing from your maps?

Oh wow yeah, I did cut off a portion of Antarctica! Thank you Adele, will fix now

**Comment by AndyHoggANU** [comment]
Hi @julia-neme -- yes, very complete, nice work!

I'm not convinced we can say which reanalysis is more accurate, but note that the plan for forcing a new experiment with ERA will use ERA5, which is an updated product from Era-Interim. Not sure how different ERA-Interim is to ERA5?

**Comment by StephenGriffies** [comment]
Yes, very nice indeed.  I do think that combining these realistic expts with idealized wind changes will be of use.

**Comment by julia-neme** [comment]
Hi @AndyHoggANU! I did ERA-Int because I still don't have membership for rt52 group, where ERA5 is stored. When I get that, should I redo this for ERA5?

**Comment by AndyHoggANU** [comment]
Yes, I think that is worthwhile. Is there a hold-up getting you access to ERA5? If there is anything I can do, let me know.
