### ISSUE TITLE
JRA55-do vs ERA5

### ISSUE THREAD

**Issue by julia-neme** [adele157/easterlies-collaborative-project#29]
I repeated #26 analysis using ERA5 now :) I believe ERA5 is more similar to JRA55 than ERA-Interim. 

The new perturbation run #28 would be a little bit trickier to set up because ERA5 has some overly large wind speeds (>50m/s) that ECMWF recommends replacing with 4m wind (https://confluence.ecmwf.int/display/CKB/ERA5%3A+large+10m+winds)

**Comment by julia-neme** [comment]
**Trends for the historical period**
*Zonal wind*
![uas-jra55_vs_era5-historical-trend](https://user-images.githubusercontent.com/51519847/127830029-d24199b1-cb35-4995-8906-c98334fad063.png)

*Meridional wind*
![vas-jra55_vs_era5-historical-trend](https://user-images.githubusercontent.com/51519847/127830068-fd78ce20-fd93-453e-985c-b368fb37e15b.png)

**Trends by season**
*Zonal wind*
![uas-jra55_vs_era5-historical-trends-seasonal](https://user-images.githubusercontent.com/51519847/127830123-4ff56c0a-2a08-4e66-a9d2-c568e14bb26f.png)

*Meridional wind*
![vas-jra55_vs_era5-historical-trends-seasonal](https://user-images.githubusercontent.com/51519847/127830155-de06d88c-b9d1-4037-9936-3a6aaafdef94.png)

**Comment by julia-neme** [comment]
**Regional time series (yearly averages)**

![basins-reference (1)](https://user-images.githubusercontent.com/51519847/127830255-c437653c-3bde-4402-ad3a-f713a81ec087.png)

*Zonal wind*
![uas_onshelf-regions-yearly-era5](https://user-images.githubusercontent.com/51519847/127830311-11afe489-663a-45ac-a13b-b2fa2dad6fc6.png)

*Meridional wind*
![vas_onshelf-regions-yearly-era5](https://user-images.githubusercontent.com/51519847/127830336-f6e67753-4ce5-469c-ab62-b6334d0b5a06.png)

**Comment by AndyHoggANU** [comment]
OK, so, it seems like the trends and patterns are now consistent between JRA and ERA, but that the magnitude is still slightly larger in JRA, in general?

Thanks for the tip about ERA. I will pass that on to Andrew and Nic.

**Comment by StephenGriffies** [comment]
Just to be sure: when you say "JRA" do you mean "JRA55-do" used to run the model, or the raw JRA55 reanalysis? Also, is it raw ERA or the modified ERA developed by DRAKKAR group?  The following paper considers these four  datasets, as well as NCEP versus CORE winds.  We did not focus on the Antarctic region, but there might be some hints as to what differences there are between the raw reanalysis versus the modified reanalysis.  

https://www.sciencedirect.com/science/article/pii/S1463500318303779?via%3Dihub

**Comment by julia-neme** [comment]
Hi @StephenGriffies, yes I am using JRA55-do and I raw ERA5 (replicated from here https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation). 

Yes @AndyHoggANU I think the patterns are now more consistent, magnitude larger for JRA55-do
