### ISSUE TITLE
JRA wind forcing

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#3]
Done:
- A notebook showing how the easterly perturbations were set up.

To do:
- It would be nice to add a plot of the zonal average 10m control and perturbed zonal wind speed to this.

**Comment by adele157** [comment]
The notebook for this is here:
https://github.com/adele157/easterlies-collaborative-project/blob/master/notebooks/forcing_perturbation/JRA_wind_perturbation_setup.ipynb

[Question: Is this the best way to link code to issues?]

**Comment by adele157** [comment]
As suggested by Matt [here](https://github.com/adele157/easterlies-collaborative-project/issues/4#issuecomment-875303811), add wind speed vector plots to this JRA wind analysis (From Matt: "I say a zoom as these wind vectors get terribly messy to plot over any large domain. Shown in CTRL and then the differenced vectors separately.")

**Comment by julia-neme** [comment]
Something like this @matthew-england-unsw ? This is wind speed and normalized wind vectors for CTRL (left), UP - CTRL (center) and DOWN - CTRL (right). In this region the dominant difference seems to be in the meridional component of the winds. Should I try other regions of interest?

![image941](https://user-images.githubusercontent.com/51519847/125224194-77927180-e310-11eb-9e83-7a2b773c3582.png)

**Comment by matthew-england-unsw** [comment]
Looks great @julia-neme , but I also have a few suggestions / questions: 
  - I assume the wind speed shading is wrong for the "DOWN" case?  Looks to be identical to the UP case?  i.e. +ve definite?
  - Can you 'white-out' all the land values?    I know I should be able to do that in my mind but I still find it distracting....  :-)
  - Can you increase the size of the arrowheads throughout?
 Thanks!

**Comment by matthew-england-unsw** [comment]
And yes, I assume this would also be useful in other regions that we're interested in?  Thanks heaps for putting this together!

**Comment by julia-neme** [comment]
> Looks great @julia-neme , but I also have a few suggestions / questions:
> 
> * I assume the wind speed shading is wrong for the "DOWN" case?  Looks to be identical to the UP case?  i.e. +ve definite?
> * Can you 'white-out' all the land values?    I know I should be able to do that in my mind but I still find it distracting....  :-)
> * Can you increase the size of the arrowheads throughout?
>   Thanks!

**Comment by julia-neme** [comment]
Edited the figures, easy to replicate for other regions!

**Comment by matthew-england-unsw** [comment]
Ahhhh LOOKS BEAUTIFUL now....!!   Thanks for sorting @julia-neme   These make the wind anomalies super clear and probably will help unravel the processes at play in any of these 'surprising response' sectors.
