### ISSUE TITLE
Temperature and salinity anomalies

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#4]
To do:

- Maps of temp/salt anomalies (averaged over years 11-15 perhaps?) at various depths (e.g. surface, 200m, 500m, bottom).

- Time series of temp/salt for different domains (perhaps select these based on what maps show).

**Comment by adele157** [comment]
The notebook for this with additional figures is here:
https://github.com/adele157/easterlies-collaborative-project/blob/master/notebooks/temp_salt_anomalies/temp_salt_anomalies.ipynb

Some interesting things to note (figures here are averaged over years 11-15):

1. DSW formation increases in the easterly increase perturbation. This is indicated by increased salinity in DSW forming regions, colder overflows and AABW downstream:
![bottom_temp_salt](https://user-images.githubusercontent.com/8506963/124698348-0b88c580-df2c-11eb-90a7-47887efa823f.jpg)

2. There is a very strong, widespread surface salinity signal (more salty in the increase perturbation, fresher in the decrease perturbation). This is particularly intense in West Antarctica and everywhere this is strongest right at the coastline. Does this indicate it is caused by increased katabatic wind-driven sea ice formation? This is the opposite change expected from the increased Ekman pumping (which would force isopycnals down against the coast with cooler and fresher waters at the surface.
<img width="1177" alt="Screen Shot 2021-07-07 at 2 05 08 pm" src="https://user-images.githubusercontent.com/8506963/124698521-5dc9e680-df2c-11eb-8402-6e76e4ecc880.png">

3. The surface temperature change is generally warming in the increase experiment and cooling in the decrease experiment. But there is a lot of spatial structure and large regions with opposite sign change:
<img width="1177" alt="Screen Shot 2021-07-07 at 2 07 44 pm" src="https://user-images.githubusercontent.com/8506963/124698712-be592380-df2c-11eb-9f68-7c5646a2230b.png">

4. One region that stands out with a large anomaly is the Amundsen Sea, with strong cooling and freshening at depth in the increase experiment (though weaker warming in the decrease experiment). See the top image of bottom properties. Any ideas as to what is causing this?

**Comment by matthew-england-unsw** [comment]
Interesting.  The weaker easterlies in the Amundsen Sea sector make this difficult to interpret without seeing a zoomed-in wind anomaly vector plot relative to CTRL in that area.   Actually, I'd love to get a sense of the precise wind anomalies we're applying in all sectors.  Maybe it's already been plotted by someone?   I say a zoom as these wind vectors get terribly messy to plot over any large domain.  Shown in CTRL and then the differenced vectors separately.

**Comment by wghuneke** [comment]
I agree with Matt in that we should have a look at the perturbed wind field. The continental shelf in the Amundsen Sea is narrow, so changes in the winds might have big impacts.

**Comment by adele157** [comment]
I've transferred the suggestion of wind speed vector plots [to the JRA wind issue here](https://github.com/adele157/easterlies-collaborative-project/issues/3#issuecomment-875373977), and made a new issue for wind stress change analysis [here](https://github.com/adele157/easterlies-collaborative-project/issues/15).

**Comment by adele157** [comment]
Copying these plots here from the [Sea Ice Issue](https://github.com/adele157/easterlies-collaborative-project/issues/10) to make them easier to find in the future. Showing that SST initially cools following the fast Ekman response in the UP simulation, but then later (by year 3) warms. The time series just shows summer SST, because in winter the SST has very minimal change, because it's so cold.

<img width="600" alt="plot1" src="https://user-images.githubusercontent.com/8506963/125703299-8a9eb983-8f4f-4cb8-b998-22bfeb9500fa.png">
<img width="969" alt="plot2" src="https://user-images.githubusercontent.com/8506963/125703320-496c4988-b3c0-4262-a7f7-4dce110d6503.png">

**Comment by adele157** [comment]
Also here's a time series of the Amundsen cooling signal in the UP perturbation.

<img width="567" alt="Screen Shot 2021-07-15 at 8 58 43 am" src="https://user-images.githubusercontent.com/8506963/125703379-e01822c9-d828-4a5d-afaf-f6966892b100.png">

**Comment by adele157** [comment]
Marking this issue as complete now, but let me know if anyone wants to see temp/salt time series in other specific regions etc.
