### ISSUE TITLE
Separate zonal/meridional perturbation simulations

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#43]
We decided yesterday to run additional perturbations where we apply only the zonal or meridional perturbations. Only a year and half so far, but looks like it is going to be interesting. The initial positive SSH on the shelf comes purely from the zonal perturbation.
<img width="500" alt="Screen Shot 2021-09-24 at 5 43 38 am" src="https://user-images.githubusercontent.com/8506963/134573640-5b4e2803-ac99-4e5c-a553-fec19f0f4555.png">
I'll update here as the run progresses.

**Comment by adele157** [comment]
Finally, here are the SWMT time series for each of the 4 DSW producing regions. In all regions, the meridional only perturbation matches the regular UP simulation pretty well, and the zonal only perturbation has very little influence on the DSW formation. In the Weddell and Adelie we do see a slight decrease in DSW formation in the zonal only perturbation.

![zonal_meridional_SWMT_regions_time_series](https://user-images.githubusercontent.com/8506963/136120115-06a89fc9-bdef-4096-8e7c-3797a5e59b79.jpg)

**Comment by matthew-england-unsw** [comment]
Very nice!!   Thanks Adele  :-)
These 'decomposition' experiments do seem to complete the study nicely.
     Regarding the zonal(-only) wind response on the shelf, wouldn't it be both?
i.e. Ekman depressing isopycnals, inducing an anomalous shelf overturning circulation [i.e. downwelling at the coast], and thereby also changing the CDW transport across the slope. This then changes the ratio of CDW to ASBW on the shelf.  Could even be some Spence et al. [2017] BBL effects?  This diagram attached below just pilfered via google isn't too bad at showing some of these processes, although it doesn't show SSH changes and it is a NH plot
![Ekman_coastal_circulation](https://user-images.githubusercontent.com/47405285/136135249-4ae49e1f-7e02-4ef4-aebe-bedc8dd7b51f.png)

**Comment by matthew-england-unsw** [comment]
Yes correct thanks Adele.  Ekman pumping can have a surprisingly rapid and detectable impact at depth. Ekman effects might appear along the shelf break within a season or two. Agreed: Isopycnal snapshots over time would help visualize this.   But when plotting I think we would need that technique of centring the x-axis along the 1000-m isobath as the zonal average is accumulated.

**Comment by adele157** [comment]
Looks like our predictions of the temperature changes in the zonal/meridional perturbations were correct: 
Overwhelmingly cooling in the zonal perturbation (due to deepening isopycnals) and overwhelmingly warming in the meridional perturbation (due to heat brought onto shelf by enhanced overturning/CDW transport). 

The main exception to this is in West Antarctica, where it also cools in the meridional experiment. Any ideas what's going on there? I guess West Antarctic transects may be helpful to understand.

Bottom temperature plots:
<img width="350" alt="Screen Shot 2021-11-22 at 11 49 56 am" src="https://user-images.githubusercontent.com/8506963/142786198-4fef4ce6-efdf-4d71-af63-6b62297cf440.png">
<img width="800" alt="Screen Shot 2021-11-22 at 11 50 24 am" src="https://user-images.githubusercontent.com/8506963/142786214-4b1c0df6-a522-49fb-80a0-dff9e69bda1a.png">

**Comment by matthew-england-unsw** [comment]
Thanks Adele.   Do you mean the shelf bottom temperatures?  Maybe it's in part because the A/B sector is unique in that it's the only shelf sector that isn't at, or downstream, of a DSW formation site?
    Even just west of the Peninsula (where meridional winds are poleward btw), that warming there is likely due to WSBW changes.  But the rest of the A/B sector is more remote from DSW formation effects.

**Comment by adele157** [comment]
Matt, yes I agree, the West Antarctic likely stands out because it’s far from a dense water site. But just interested in then what’s the mechanism driving the cooling there in the meridional wind case?
