### ISSUE TITLE
DSW export across slope

### ISSUE THREAD

**Issue by julia-neme** [adele157/easterlies-collaborative-project#46]
It was suggested to [calculate export of DSW across some isobath](https://github.com/adele157/easterlies-collaborative-project/issues/37#issuecomment-939807439) because of the little changes observed in [MOC](https://github.com/adele157/easterlies-collaborative-project/issues/6#issuecomment-939782765).

I've had a go at it, but I'm not sure its ok, you can see the [code here](https://github.com/adele157/easterlies-collaborative-project/blob/b8c75aeb39f2821d652ec69f9f6e749807261750/notebooks/moc/DSW-export-sigma1.ipynb). What I did was in summary:
1. Used mass transport `tx_trans` and `ty_trans` to calculate transport normal to the 1500m isobath. I used 1500m for convenience because the file is already created, if necessary it could be changed to 2000m.
2. Calculated sigma1 from temperature and salinity fields
3. I looked at the transport for the density range corresponding to DSW (sigma1>32.5)

This is the test result for one random year of the control simulation:

![test](https://user-images.githubusercontent.com/51519847/137043769-f1f596ff-0c29-43ae-a203-84df19e8f483.jpg)

Everything down from the black contour (==32.5 in sigma1) "would" be DSW? I think this is a too broad classification (that's it if I haven't made any mistakes coding), and if I sum everything in that range, the resulting transport is negative, which means its *onto* the continental shelf. 

If anyone has suggestions or wants to have a go at this, please feel free :)

**Comment by adele157** [comment]
Ah yes sorry, this needs to be done using daily data, because otherwise you’ll miss some of the dense water in the binning using only monthly fields. I will compute and point you to the processed output.

**Comment by adele157** [comment]
Actually, I just went to start processing the daily output (for the DSW transport time series across the 1000m isobath) and remembered that we never saved the dailies for the control (we do have them for all the perturbations though). Perhaps we can look at how the cross-slope DSW transport looks in the UP and DOWN first and then if we really want it for the control, we can rerun. Not sure we have the hours to spare now though. Any thoughts?

**Comment by matthew-england-unsw** [comment]
Good call Adele, based on some of the metrics we’ve been looking at (I.e., their overall linearity) a difference plot UP minus DOWN should work fine as a quick look

**Comment by wghuneke** [comment]
Do we know how much variability there is in RYF? Could we use other years when we have the daily output?
