### ISSUE TITLE
Schematic illustration

### ISSUE THREAD

**Issue by wghuneke** [adele157/easterlies-collaborative-project#49]
Option 1: Schematic to introduce the three different mechanisms we suggest.
Option 2: Summarising schematic at end of paper.

**Comment by wghuneke** [comment]
A very first and rough attempt for schematic summarising the processes active in the perturbation experiments:
![Screenshot_Schematic_Easterlies](https://user-images.githubusercontent.com/15355753/141384203-bb547eeb-6549-4573-803f-19224066f29c.png)

**Comment by AndyHoggANU** [comment]
Very nice -- I would say appropriate for option 2, as many of the mechanisms on the RHS will require the reader to understand the full set of experiments ...

**Comment by adele157** [comment]
I'm including this work in a seminar I'm giving tomorrow, so made some schematics to include in my talk. Not sure if this is what we want for paper or not though. I had trouble fitting brine rejection in. And have yet to check if the temperature changes from the zonal/meridional perturbations match this (oops, should really have done that first!).

Easterlies mechanism:
<img width="500" alt="easterly_schematic" src="https://user-images.githubusercontent.com/8506963/142783856-7443cccd-01fd-4980-aff0-020c34649eb1.jpg">

Northerlies mechanism:
<img width="500" alt="northerly_schematic" src="https://user-images.githubusercontent.com/8506963/142783756-5bec9d7e-46c6-4340-9661-ad88828b8bdd.jpg">

**Comment by adele157** [comment]
Actually, have updated the zonal one to be representative of the temperature anomaly, to match the meridional one (when I first made the zonal one I was thinking about explaining/showing the background control temperature gradient, rather than the change):

<img width="500" alt="easterly_schematic_cooling" src="https://user-images.githubusercontent.com/8506963/142790343-a912f02d-d1fe-4084-931e-4709fa56d2af.jpg">

**Comment by matthew-england-unsw** [comment]
Very nice!!

**Comment by AndyHoggANU** [comment]
I agree, looking good. 
BTW, I can confirm that ice volume does decrease in the WIND+ case - I went to calculate this and it was already done in one of Paul's notebooks. The ice volume goes down by about 5e10m^3 - mostly in the first year, and the remainder in the second year. In contrast, the net melt is ~0.01 Sv, which is ~1e9m^3/day. So the change in ice volume is about ~50 days of net melt. But it only really happens in the first year, so I would say this is a good indication that the net melt is not a reflection of changing ice volume ...
