### ISSUE TITLE
Reviewer 2 response

### ISSUE THREAD

**Issue by adele157** [adele157/easterlies-collaborative-project#75]
"Very few studies explain what is done with the coarse JRA55do atmospheric forcing along the Antarctic margin. I think that it would be important to provide this information, especially in a study focusing on coastal winds. For example, some groups extrapolate the atmospheric properties from JRA55do’s ocean points to the ocean model grid points that would otherwise be under JRA55do’s cold and dry over-ice-sheet conditions. The interpolation method itself (e.g., linear, cubic) is also worth a mention."

@aekiss, @AndyHoggANU any input here? What interpolation method do we use from JRA to the ACCESS-OM2? And is anything special done for this interpolation near coasts to ensure separation of over ice/land atmosphere conditions from over ocean atmosphere conditions?

**Comment by aekiss** [comment]
We don't do anything special at the coasts, but it sounds like we probably should.

We use different interpolation methods: conservative for fluxes, smooth (e.g. "patch" method) for velocities. See your `namcouple` for details.
